import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, query, where, orderBy, deleteDoc, doc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-storage.js";
import { firebaseConfig, adminEmails } from "./firebase-config.js";
let app,auth,db,storage,currentUser;function isAdmin(u){return u&&adminEmails.map(e=>e.toLowerCase()).includes(u.email.toLowerCase())}
function init(){if(firebaseConfig.apiKey.includes("PUT_")){loginMsg.textContent="اربطي Firebase لتفعيل الإدارة.";return false}app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);storage=getStorage(app);return true}
async function load(){const snap=await getDocs(query(collection(db,"archive_items"),where("status","==","approved"),orderBy("createdAt","desc")));publishedStatus.textContent=`${snap.size} منشور`;publishedList.innerHTML=snap.docs.map(d=>{const x=d.data();return `<div class="adminRow"><div><b>${x.title}</b><br><small>${x.type||""} - ${x.location||""}</small></div><button class="delete" data-id="${d.id}">حذف</button></div>`}).join("")||"<p>لا يوجد محتوى.</p>";document.querySelectorAll("[data-id]").forEach(b=>b.onclick=async()=>{if(confirm("حذف؟")){await deleteDoc(doc(db,"archive_items",b.dataset.id));load()}})}
if(init()){onAuthStateChanged(auth,u=>{currentUser=u;loginBox.classList.toggle("hidden",!!u);logoutBtn.classList.toggle("hidden",!u);if(!u)return;if(!isAdmin(u)){loginMsg.textContent="الحساب ليس إدارة.";return}adminBox.classList.remove("hidden");publishedBox.classList.remove("hidden");load()});loginForm.onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,email.value,password.value)}catch(err){loginMsg.textContent="تعذر الدخول"}};logoutBtn.onclick=()=>signOut(auth);contentForm.onsubmit=async e=>{e.preventDefault();try{let fileUrl="",fileType="";const f=file.files[0];if(f){fileType=f.type;const fileRef=ref(storage,`approved/${Date.now()}-${f.name.replaceAll(" ","-")}`);await uploadBytes(fileRef,f);fileUrl=await getDownloadURL(fileRef)}await addDoc(collection(db,"archive_items"),{title:title.value,date:date.value,location:location.value,region:region.value,type:type.value,desc:desc.value,fileUrl,fileType,status:"approved",createdAt:serverTimestamp(),createdByEmail:currentUser.email});contentForm.reset();saveMsg.textContent="تم النشر.";load()}catch(err){saveMsg.textContent=err.message}}}
