import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { getAuth, signInWithEmailAndPassword, createUserWithEmailAndPassword, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js";
import { getFirestore, collection, addDoc, getDocs, query, where, orderBy, serverTimestamp, doc, getDoc, setDoc } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-storage.js";
import { firebaseConfig } from "./firebase-config.js";
const loginBox=document.getElementById("loginBox"),memberBox=document.getElementById("memberBox"),myBox=document.getElementById("myBox"),blockedBox=document.getElementById("blockedBox"),logoutBtn=document.getElementById("logoutBtn");const loginMsg=document.getElementById("loginMsg"),saveMsg=document.getElementById("saveMsg"),myList=document.getElementById("myList"),myStatus=document.getElementById("myStatus");let app,auth,db,storage,currentUser;
function init(){if(firebaseConfig.apiKey.includes("PUT_")){loginMsg.textContent="لم يتم وضع بيانات Firebase بعد.";return false}app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app);storage=getStorage(app);return true}
async function ensureProfile(user){const r=doc(db,"members",user.uid);const s=await getDoc(r);if(!s.exists())await setDoc(r,{email:user.email,uid:user.uid,role:"member",blocked:false,createdAt:serverTimestamp()});return (await getDoc(r)).data()}
async function loadMine(){const snap=await getDocs(query(collection(db,"archive_items"),where("createdBy","==",currentUser.uid),orderBy("createdAt","desc")));myStatus.textContent=`${snap.size} إضافة`;myList.innerHTML=snap.docs.map(d=>{const x=d.data();const status=x.status==="approved"?"معتمد":x.status==="rejected"?"مرفوض":"بانتظار المراجعة";return `<div class="adminRow"><div><b>${x.title}</b><br><small>${x.type||""} - ${x.location||""} - ${x.date||""}</small><br><span class="badge">${status}</span></div></div>`}).join("")||"<p>لم تضيفي محتوى بعد.</p>"}
if(init()){onAuthStateChanged(auth,async user=>{currentUser=user;loginBox.classList.toggle("hidden",!!user);logoutBtn.classList.toggle("hidden",!user);if(!user){memberBox.classList.add("hidden");myBox.classList.add("hidden");blockedBox.classList.add("hidden");return}const profile=await ensureProfile(user);if(profile.blocked){blockedBox.classList.remove("hidden");memberBox.classList.add("hidden");myBox.classList.add("hidden");return}blockedBox.classList.add("hidden");memberBox.classList.remove("hidden");myBox.classList.remove("hidden");loadMine()});
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();loginMsg.textContent="جاري الدخول...";try{await signInWithEmailAndPassword(auth,email.value,password.value);loginMsg.textContent=""}catch(err){loginMsg.textContent="تعذر الدخول. تأكدي من البريد وكلمة المرور."}});
document.getElementById("registerBtn").onclick=async()=>{loginMsg.textContent="جاري إنشاء الحساب...";try{await createUserWithEmailAndPassword(auth,email.value,password.value);loginMsg.textContent="تم إنشاء الحساب."}catch(err){loginMsg.textContent="تعذر إنشاء الحساب: "+err.message}};logoutBtn.onclick=()=>signOut(auth);
document.getElementById("contentForm").addEventListener("submit",async e=>{e.preventDefault();saveMsg.textContent="جاري إرسال المحتوى للمراجعة...";try{const profile=await ensureProfile(currentUser);if(profile.blocked)throw new Error("الحساب محظور");let fileUrl="",fileType="";const f=document.getElementById("file").files[0];if(f){fileType=f.type;const safeName=`${Date.now()}-${f.name.replaceAll(" ","-")}`;const fileRef=ref(storage,`pending/${currentUser.uid}/${safeName}`);await uploadBytes(fileRef,f);fileUrl=await getDownloadURL(fileRef)}await addDoc(collection(db,"archive_items"),{title:title.value,date:date.value,location:location.value,region:region.value,type:type.value,desc:desc.value,fileUrl,fileType,status:"pending",createdBy:currentUser.uid,createdByEmail:currentUser.email,createdAt:serverTimestamp()});e.target.reset();saveMsg.textContent="تم الإرسال. سيظهر للعامة بعد اعتماد الإدارة.";loadMine()}catch(err){saveMsg.textContent="حدث خطأ: "+err.message}})}
